os:
  - linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
- docker

# build for all pushes, as well as PRs coming from forks
# this ensures that the pipeline is triggered for internal pushes,
# PRs from forks and pushes to existing PRs from forks
if: (type == push) OR (type == pull_request AND fork == true)

stages:
- name: test
- name: publish
  # for security reasons, builds from forks won't be published until merged;
  # also, environment variables defined in repository settings are not
  # available to builds from PRs coming from external repos
  if: fork == false

before_script:
  - |
    if [ "$TRAVIS_BRANCH" = "dev" ]; then
        export DOCKER_TAG="$(date '+%Y%m%d')"
    else
        export DOCKER_TAG=${TRAVIS_BRANCH//_/-}
        export DOCKER_TAG=${DOCKER_TAG//\//-}
    fi

jobs:
  include:
    - stage: test
      name: Linter, unit & integration tests
      script:
        - flake8
        - coverage run --source foca -m pytest
        - coveralls
    - stage: build
      name: Docker build test
      script:
        - docker build .
    - stage: publish
      name: Build and publish
        - docker build . -t "${DOCKER_REPO_NAME}:latest" -t "${DOCKER_REPO_NAME}:${DOCKER_TAG}"
        - echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push "${DOCKER_REPO_NAME}:${DOCKER_TAG}"
        - if [ "$TRAVIS_BRANCH" = "dev" ]; then docker push "${DOCKER_REPO_NAME}:latest"; fi
        - rm ${HOME}/.docker/config.json  # delete token
