log:
    version: 1
    disable_existing_loggers: False
    formatters:
        standard:
            class_handler: logging.Formatter
            style: "{"
            format: "[{asctime}: {levelname:<8}] {message} [{name}]"
    handlers:
        console:
            class_handler: logging.StreamHandler
            level: logging.DEBUG
            formatter: standard
            stream: ext://sys.stderr
    root:
        level: INFO
        handlers: [console]
