version: '3.6'
services:

  app:
    image: foca:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongodb
    command: bash -c "cd /basic-app;python3 app.py"
    ports:
      - "7777:8080"

  mongodb:
    image: mongo:3.2
    restart: unless-stopped
    ports:
      - "27017:27017"
